setwd("~/Desktop")
data<-read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
data$Datetime <- strptime(paste(data$Date, data$Time), "%d/%m/%Y %H:%M:%S")
dat<-subset(data,Date=="2/2/2007"|Date=="1/2/2007")
plot(dat$Datetime,dat$Global_active_power,type="l",xlab="",ylab="Global Active Power(kilowatts)")